### ISSUE TITLE
XADES-XL

### ISSUE THREAD

**Issue by sangar82** [bseddon/xml-signer#7]
Hi @bseddon !

Any news about XADES-XL progress??

Thank you!

**Comment by sangar82** [comment]
@bseddon reading the documentation I've found this:
https://github.com/esig/dss/blob/master/dss-cookbook/src/main/asciidoc/dss-documentation.adoc#xades-baseline-lt

There are some examples:
https://github.com/esig/dss/blob/master/dss-cookbook/src/main/asciidoc/_samples/xades-revocation-data.adoc
https://github.com/esig/dss/blob/master/dss-cookbook/src/main/asciidoc/_samples/xades-archive-timestamp.adoc

Can it help you?

**Comment by bseddon** [comment]
These are not so good for me.  These documents are confirming what elements should be included but this is covered in the specification.  So I know what **should** go into the signature but I can't be 100% sure the way I am reading the specification is correct.  The '.adoc. links show fragments from a signature.  But how was it decided that those **values** should be included?

With access to a full signature that is accepted by the EU commission demo web app or the XAdES conformance checker I will be able to apply my reading of the specification to the document to see I generate the same values.  If not, I can try to better understand what the specification really says.

Right now I am writing code that I think implements the specification which I will be able to test.  But if the generated signature is not accepted by any of the validators then I have to scratch my head and try to find what I have done wrong.  Is the code wrong or have I misunderstood what the specification says.

I am really surprised there are no complete signatures provided by ETSI for all profiles (-B, -T, -LT, -LTA etc,).  I have written to ask if there are any but I've no had a response yet.

**Comment by bseddon** [comment]
Or take this example from the [DSS GitHub page](https://github.com/esig/dss/blob/master/dss-cookbook/src/test/resources/signature-pool/signedXmlXadesLT.xml) (which I saved as a file and attached) - it does not validate on the DSS web app site (at least for me)

Usually support for conformance testing is critically important.  Major standards (XML, XPath, XQuery, etc.) come with huge test libraries so implementers are able to ensure their code is able to produce the correct output.  This doesn't seem to be the case with XAdES.  Ah,well, hopefully the way I am reading the specification is correct and the signatures produced will be great!
[signedXmlXadesLT.zip](https://github.com/bseddon/xml-signer/files/7353630/signedXmlXadesLT.zip)
.

**Comment by bseddon** [comment]
The code grabs a copy the full certificate chain of all certificates used (for signing and timestamping).  However, this assumes a certificate used includes information about it's issuer (CA).  Almost all do as there is a specific variable in a certificate (called an 'extension' in the jargon) for this URL.  

If a certificate does not include information about how to access it's issuer then this can be added to the certificate PEM file referenced by the CertificateResourceInfo class.  All certificates in this PEM file are added to the ./KeyInfo/X509Data element when the signature is created.

**Comment by sangar82** [comment]
Ok! @bseddon ! I understand this! 

Another question:
- If you don't add a new SignatureTimeStamp, it will produce a Xades-baseline-LT format? Could be interesting produce it if is easy. p.ex with another method.
Thank you!!

**Comment by sangar82** [comment]
Thanks to you Bill! If you come to Girona let me know and we will celebrate this great package! Thank you!
